services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./backend/.docker/local/app/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    working_dir: /app
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # depends_on:
    #   mysql:
    #     condition: service_healthy
